base:
  project: BigMart-Sales-Prediction-MLops
  random_state: 42
  target_col: Item_Outlet_Sales

data_source:
  remote_source: data_given/train.csv

load_data:
  raw_dataset_csv: data/raw/train.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.1
      l1_ratio: 0.2
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib